export const translations = {
  en: {
    // Menu items
    overview: 'Overview',
    caseManagement: 'Case Management',
    documentsCase: 'Documents Case',
    aiDocuments: 'AI Documents',
    aiSystem: 'AI System',
    legalInformation: 'Legal Information',
    settings: 'Settings',
    
    // Main menu
    mainMenu: 'Main Menu',
    
    // Header
    search: 'Search...',
    light: 'Light',
    dark: 'Dark',
    ttc: 'TTC',
    
    // Profile menu
    editProfile: 'Edit Profile',
    viewHistory: 'View History',
    logout: 'Log out',
    
    // History
    generationHistory: 'Generation History',
    openInChat: 'Open in Chat',
    aiHistory: 'AI History',
    persistentHistory: 'Persistent History',
    
    // Overview
    dashboardOverview: 'Dashboard Overview',
    switchCase: 'Switch Case',
    activeCases: 'Active Cases',
    documentsGenerated: 'Documents Generated',
    aiConsultations: 'AI Consultations',
    legalResearch: 'Legal Research',
    currentCase: 'Current case',
    currentCaseDocuments: 'Current Case Documents',
    totalDocuments: 'Total Documents',
    aiGeneratedDocuments: 'AI Generated Documents',
    casesInProgress: 'Cases in progress',
    acrossAllCases: 'Across all cases',
    generatedByAI: 'Generated by AI',
    thisWeek: '+3 this week',
    thisMonth: '+15 this month',
    hoursSaved: 'Hours saved',
    generatedFiles: 'Generated Files for',
    noFilesGenerated: 'No files generated yet',
    generateDocuments: 'Generate Documents',
    generateNewDocument: 'Generate New Document for This Case',
    recentLegalActivity: 'Recent Legal Activity',
    recentAIActivity: 'Recent AI Activity',
    quickStats: 'Quick Stats',
    clickToViewAll: 'Click to view all',
    goTo: 'Go to',
    noAIActivity: 'No AI activity yet',
    startAIWork: 'Start AI Work',
    manageAllCases: 'Manage All Cases',
    avgDocumentsPerCase: 'Avg documents per case',
    aiSessionsToday: 'AI sessions today',
    
    // AI Documents
    aiLegalDocuments: 'AI Legal Documents',
    documentContent: 'Document Content',
    aiLegalAssistant: 'AI Legal Assistant',
    active: 'Active',
    backToDocuments: '← Back to Documents',
    askAiToAnalyze: 'Ask AI to analyze, rewrite, or improve the legal document...',
    aiIsAnalyzing: 'AI is analyzing document...',
    analyzeLegalRisks: 'Analyze legal risks',
    rewriteDocument: 'Rewrite document',
    improveStructure: 'Improve structure',
    addLegalClauses: 'Add legal clauses',
    openWithAi: 'Open with AI Legal Assistant',
    
    // Case fields
    fio: 'Full Name',
    patronymic: 'Patronymic',
    iin: 'IIN',
    organization: 'Organization',
    investigator: 'Investigator',
    registrationDate: 'Registration Date',
    qualification: 'Qualification',
    damageAmount: 'Damage Amount',
    incomeAmount: 'Income Amount',
    indictmentDate: 'Indictment Date',
    createdAt: 'Created At',
    updatedAt: 'Updated At',
    
    // Common
    copy: 'Copy',
    download: 'Download',
    size: 'Size',
    type: 'Type',
    modified: 'Modified',
    view: 'View',
    poweredBy: 'JSC "TransTelecom" • For AFM KNB',
    language: 'Language',
    theme: 'Theme',
    
    // Activities
    generatedContract: 'Generated contract',
    caseAnalysisCompleted: 'Case analysis completed',
    legalBriefCreated: 'Legal brief created',
    documentReviewFinished: 'Document review finished',
    hoursAgo: 'hours ago',
    dayAgo: 'day ago',
    daysAgo: 'days ago',
    
    // Mobile
    menu: 'Menu',
    close: 'Close'
  },
  ru: {
    // Menu items
    overview: 'Обзор',
    caseManagement: 'Управление Делами',
    documentsCase: 'Документы по Делу',
    aiDocuments: 'ИИ Документы',
    aiSystem: 'ИИ Система',
    legalInformation: 'База данных',
    settings: 'Настройки',
    
    // Main menu
    mainMenu: 'Главное Меню',
    
    // Header
    search: 'Поиск...',
    light: 'Светлая',
    dark: 'Темная',
    ttc: 'TTC',
    
    // Profile menu
    editProfile: 'Редактировать Профиль',
    viewHistory: 'Посмотреть Историю',
    logout: 'Выйти',
    
    // History
    generationHistory: 'История Генерации',
    openInChat: 'Открыть в Чате',
    aiHistory: 'История ИИ',
    persistentHistory: 'Постоянная История',
    
    // Overview
    dashboardOverview: 'Обзор Панели',
    switchCase: 'Сменить Дело',
    activeCases: 'Активные Дела',
    documentsGenerated: 'Сгенерированы Документы',
    aiConsultations: 'ИИ Консультации',
    legalResearch: 'Юридические Исследования',
    currentCase: 'Текущее дело',
    currentCaseDocuments: 'Документы по Текущему Делу',
    totalDocuments: 'Общие Документы',
    aiGeneratedDocuments: 'ИИ Документы',
    casesInProgress: 'Дела в работе',
    acrossAllCases: 'По всем делам',
    generatedByAI: 'Сгенерировано ИИ',
    thisWeek: '+3 на этой неделе',
    thisMonth: '+15 в этом месяце',
    hoursSaved: 'Часов сэкономлено',
    generatedFiles: 'Сгенерированные Файлы для',
    noFilesGenerated: 'Файлы ещё не сгенерированы',
    generateDocuments: 'Генерировать Документы',
    generateNewDocument: 'Сгенерировать Новый Документ для Этого Дела',
    recentLegalActivity: 'Недавняя Юридическая Активность',
    recentAIActivity: 'Недавняя ИИ Активность',
    quickStats: 'Быстрая Статистика',
    clickToViewAll: 'Нажмите для просмотра всех',
    goTo: 'Перейти',
    noAIActivity: 'Пока нет активности ИИ',
    startAIWork: 'Начать работу с ИИ',
    manageAllCases: 'Управление Всеми Делами',
    avgDocumentsPerCase: 'Среднее документов на дело',
    aiSessionsToday: 'ИИ сессии сегодня',
    
    // AI Documents
    aiLegalDocuments: 'ИИ Юридические Документы',
    documentContent: 'Содержание Документа',
    aiLegalAssistant: 'ИИ Юридический Ассистент',
    active: 'Активен',
    backToDocuments: '← Назад к Документам',
    askAiToAnalyze: 'Попросите ИИ проанализировать, переписать или улучшить юридический документ...',
    aiIsAnalyzing: 'ИИ анализирует документ...',
    analyzeLegalRisks: 'Анализ юридических рисков',
    rewriteDocument: 'Переписать документ',
    improveStructure: 'Улучшить структуру',
    addLegalClauses: 'Добавить юридические пункты',
    openWithAi: 'Открыть с ИИ Юридическим Ассистентом',
    
    // Case fields
    fio: 'ФИО',
    patronymic: 'Отчество',
    iin: 'ИИН',
    organization: 'Организация',
    investigator: 'Следователь',
    registrationDate: 'Дата Регистрации',
    qualification: 'Квалификация',
    damageAmount: 'Сумма Ущерба',
    incomeAmount: 'Сумма Дохода',
    indictmentDate: 'Дата Обвинительного Заключения',
    createdAt: 'Создано',
    updatedAt: 'Обновлено',
    
    // Common
    copy: 'Копировать',
    download: 'Скачать',
    size: 'Размер',
    type: 'Тип',
    modified: 'Изменено',
    view: 'Просмотр',
    poweredBy: 'АО "ТрансТелеком"',
    language: 'Язык',
    theme: 'Тема',
    
    // Activities
    generatedContract: 'Сгенерирован договор',
    caseAnalysisCompleted: 'Завершен анализ дела',
    legalBriefCreated: 'Создана юридическая справка',
    documentReviewFinished: 'Завершен обзор документа',
    hoursAgo: 'часов назад',
    dayAgo: 'день назад',
    daysAgo: 'дней назад',
    
    // Mobile
    menu: 'Меню',
    close: 'Закрыть'
  }
};

export interface Message {
  id: string;
  text: string;
  sender: 'user' | 'ai';
  timestamp: Date;
}

export interface GenerationHistory {
  id: string;
  caseId: string;
  caseName: string;
  documentType: string;
  timestamp: Date;
  context: any;
  section: string; // Track which section it was created in
  persistent?: boolean; // For long-term storage
  aiType?: 'qualifier' | 'completeness' | 'legal' | 'evidence' | 'unified';
  messageCount?: number; // Track conversation length
  lastAccessed?: Date; // Track when last opened
}

export interface CaseData {
  id: string;
  fio: string;
  patronymic: string;
  iin: string;
  organization: string;
  investigator: string;
  registration_date: Date;
  qualification: string;
  damage_amount: number;
  income_amount: number;
  indictment_date: Date;
  created_at: Date;
  updated_at: Date;
  // Legacy fields for display
  name: string;
  type: string;
  status: string;
  client: string;
  priority: 'High' | 'Medium' | 'Low';
  deadline: string;
  description: string;
  generatedFiles: Array<{
    id: string;
    name: string;
    type: string;
    generatedAt: Date;
    size: string;
  }>;
  documents: Array<{
    id: string;
    name: string;
    type: string;
    category: string;
    size: string;
    uploadDate: Date;
    uploadedBy: string;
    content?: string;
  }>;
}

export interface SectionProps {
  onNavigate?: (section: string, context?: any) => void;
  selectedCase?: string;
  casesData?: CaseData[];
  onCaseChange?: (caseId: string, documentType?: string) => void;
  onAddToHistory?: (documentType: string) => void;
  generationHistory?: GenerationHistory[];
}